@startuml Chess
Class Chess{
    + play()
    + isResumed()
}
Chess *--> Turn 
Class Turn{
    + active : int
    + noActive : int
    + change()
}
Turn --> "2" Player
Chess *--> Board
Class Board{
    - squares : Square[]
    + show()
    - setSquares()
    - getSquare(Coordenate) : char
}
Board o--> Square
Board o--> "2" Player
Class Square{
    + Code
}
Square *--> Coordenate
Class Player{
    + pieces[] : Piece
    + movePiece()
}
Piece *--> Coordenate
Player --> Piece
Class Piece{
    + Player : Color
    + move()
}
Piece <|-- King
Piece <|-- Queen
Piece <|-- rook
@enduml